MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: FPN.add_fpn_ResNet50_conv5_body
  NUM_CLASSES: 81
  RPN_ONLY: False
  FASTER_RCNN: True
  CASCADE_ON: False
  CLS_AGNOSTIC_BBOX_REG: True  # default: False
  ROI_2CLS_ON: False
  ROI_81CLS_ON: False
  ROI_2CLS_LOSS_OFF: False
  ROI_HARD_NEG_ON: False
  ROI_HARD_POS_ON: False
  ALL_ROI_ON: False
  DECOUPLE_CLS_REG: False
  FINE_FEATURE_ON: False
  PATCH_FEATURE_ON: False
  PATCH_FEATURE_81CLS_ON: False
  DEEP_SUP_ON: False
  DEEP_SUP_RPN_ON: False
  SPECIFIC_CLS_HEAD_ON: False
NUM_GPUS: 1
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.0025
  GAMMA: 0.1
  MAX_ITER: 6500
  STEPS: [0, 4300, 5700]
FPN:
  FPN_ON: True
  MULTILEVEL_ROIS: True
  MULTILEVEL_RPN: True
FAST_RCNN:
  ROI_BOX_HEAD: fast_rcnn_heads.add_roi_2mlp_head #add_roi_2mlp_decouple_head #add_roi_2mlp_head
  ALL_ROI_BOX_HEAD: fast_rcnn_heads.add_all_roi_2mlp_decouple_head #add_all_roi_2mlp_head
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 7
  ROI_XFORM_SAMPLING_RATIO: 2
ROI_81CLS:
  ROI_BOX_HEAD: roi_81_cls_heads.add_roi_2mlp_head #add_roi_2mlp_head_lateral_fpn #add_roi_2mlp_head
ROI_DEEP_SUP:
  ROI_BOX_HEAD: roi_deep_sup_heads.add_roi_2mlp_head
ROI_SPECIFIC_CLS:
  ROI_BOX_HEAD: roi_specific_cls_heads.add_roi_2mlp_head
#  SPECIFIC_CLS: 2
CASCADE_RCNN:
  ROI_BOX_HEAD: cascade_rcnn_heads.add_roi_2mlp_decouple_head #add_roi_2mlp_head
  NUM_STAGE: 3
  TEST_STAGE: 3
  TEST_ENSEMBLE: False
TRAIN:
  WEIGHTS: ./pretrained_model/R-50.pkl #./tmp/25/train/coco_2014_train/generalized_rcnn/model_iter59999.pkl #./pretrained_model/R-50.pkl #  #./tmp/17/train/coco_2014_train/generalized_rcnn/model_iter59999.pkl #/media/fanyang/C/code/detector/Detectron-Cascade-RCNN/tmp/10/train/coco_2014_train/generalized_rcnn/model_iter3999.pkl
  DATASETS: ('coco_2014_val', )
  SCALES: (600,)
  MAX_SIZE: 1000
  BATCH_SIZE_PER_IM: 512
  RPN_PRE_NMS_TOP_N: 2000  # Per FPN level
  RPN_POST_NMS_TOP_N: 2000
#  RPN_POSITIVE_OVERLAP: 0.5
#  RPN_BATCH_SIZE_PER_IM: 1024
#  SNAPSHOT_ITERS: 2000
TEST:
  DATASETS: ('coco_2014_val',)
  SCALE: 600
  MAX_SIZE: 1000
  NMS: 0.5
  RPN_PRE_NMS_TOP_N: 1000  # Per FPN level
  RPN_POST_NMS_TOP_N: 1000
#  DETECTIONS_PER_IM: 300
OUTPUT_DIR: .
VIS: False
VIS_TH: 0.1

